### ISSUE TITLE
Support hashicorp/google 5.0.0

### ISSUE THREAD

**Issue by kuzmik** [terraform-google-modules/terraform-google-container-vm#116]
### TL;DR

The google 5.0 provider was released this week, and we've been migrating our terraform to use it. However, we have a dozen or so places where we use this module, and since it is pinning to `google < 5.0` we are unable to upgrade.

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/5.0.0
```

### Detailed design

```hcl
terraform {
  required_version = "~> 1.6.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0.0" #
    }
    cloudinit = {
      source  = "hashicorp/cloudinit"
      version = ">= 2.3.0"
    }
  }
}

provider "google" {
  project = "persona-web-development"
  region  = "us-central1"
}


module "gce-container" {
  source  = "terraform-google-modules/container-vm/google"
  version = "~> 3.1"

  cos_image_name = null

  container = {
    image = "stefanprodan/podinfo:latest"
  }

  restart_policy = "Always"
}
```

### Additional information

```
13:27:34 <nick@arcadia:infrastructure/compute/ian-redcanary-test(main)(!) $ > tf init -upgrade

Initializing the backend...
Upgrading modules...
Downloading registry.terraform.io/terraform-google-modules/container-vm/google 3.1.0 for gce-container...
- gce-container in /Users/nick/.local/share/terraform/modules/gce-container

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding hashicorp/cloudinit versions matching ">= 2.3.0"...
- Finding hashicorp/google versions matching ">= 3.53.0, ~> 5.0.0, < 5.0.0"...
- Using previously-installed hashicorp/cloudinit v2.3.2
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/google: no available releases match the given constraints >= 3.53.0, ~> 5.0.0, < 5.0.0
╵
```

**Comment by leorimmer** [comment]
5.1.0 is required actually, because of bug fixes.

**Comment by victorbiga** [comment]
experiencing the same problem when can this be looked at https://github.com/terraform-google-modules/terraform-google-container-vm/pull/119 ?

**Comment by AndreasKillaitis0000** [comment]
Any update on this? Our team needs this to be resolved, as we have lots of microservices we cannot switch to Google provider 5.

**Comment by Klaitos** [comment]
Tips: For those waiting (as me) for this issue to be fixed, you can migrate all yours resources that need something from google provider 5.0+ to `google-beta` provider. Then you can switch back to original one when this issue is resolved.

**Comment by enricojonas** [comment]
We are also waiting for this. Probably the constraint should be set to ">= 3.53, < 6.0" or similar as already mentioned.

**Comment by ianchesal** [comment]
This is embarrassing, Google. These are your "official" modules and you can't keep them up to date with your official provider releases?

**Comment by devodev** [comment]
Bump. Please prioritize this. Thanks!
