### ISSUE TITLE
Getting exception: use google beta provider for MIG module

### ISSUE THREAD

**Issue by arvindpai** [terraform-google-modules/terraform-google-container-vm#15]
Error: module.mig.google_compute_instance_group_manager.default: "auto_healing_policies": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

**Comment by morgante** [comment]
I think this might be filed on the wrong module? This module doesn't include any reference to auto healing policies.

**Comment by morgante** [comment]
Closing since the referenced code isn't from this module.
