### ISSUE TITLE
pin cos image, or ok to ignore source_image and vm_container_label outputs?

### ISSUE THREAD

**Issue by joshk0** [terraform-google-modules/terraform-google-container-vm#37]
Hello from LiveRamp!

This module outputs a `source_image` and `vm_container_label` value which seem to be synced together. According to the examples, you're supposed to instantiate the resulting VM with that source image, and label the VM with container-vm=$vm_container_label.

However, the source image (cos) updates far too frequently for our taste, and we want to pin it to something so we can take updates on a schedule we control. Is there a way to pin the source image / would it be safe to?

Alternatively, can we just ignore those outputs as long as we are using a sufficiently new version of cos? Is there even semantic value to setting that container-vm or is it just informational? It's not clear how the GCE feature is implemented, so i'm asking to avoid some fun surprises down the line.

Thanks!

**Comment by morgante** [comment]
It's not necessarily recommended to use an old version of the COS image (since it is updated frequently specifically to accommodate new features)

We could expose an option to pin the source image to a specific named image. Would that be sufficient?

Setting the container-vm label helps GCE to know this VM is meant to run an image.

**Comment by aaron-lane** [comment]
@joshk0 does the proposed solution satisfy your use case?

**Comment by joshk0** [comment]
> We could expose an option to pin the source image to a specific named image. Would that be sufficient?

yep, this would work for us! Sorry for the dropped ball here.
