### ISSUE TITLE
Updating image inside the example doesn't cause container to restart

### ISSUE THREAD

**Issue by denys1yermakov** [terraform-google-modules/terraform-google-container-vm#45]
https://github.com/terraform-google-modules/terraform-google-container-vm/issues/29

the issue is still valid

Changing the image name should cause a new container to be spun up.
Reproduction:
1. Open the simple-example
2. Run terraform apply
3. Change the image ID
4. Run terraform apply again - the new container should be started instead.

**Comment by kopachevsky** [comment]
@denys1yermakov  is it actually working? what was your confusion than?

**Comment by kopachevsky** [comment]
I see, original issue 29 is reopened, thanks
