### ISSUE TITLE
Is indentation difference in container metadata a problem?

### ISSUE THREAD

**Issue by svachmic** [terraform-google-modules/terraform-google-container-vm#52]
I have defined a VM in GCP, running a Memcached container. Now I am in the middle of importing all of the infrastructure into Terraform. There is one little problem that I am afraid of simply ignoring and that is the indentation of the generated YAML while running terraform plan.

To give a little context - the Memcached VM was launched using the **GCP Launcher**. I created a bare minimum resource in TF, imported it and now I'm backtracking and trying to add all missing data into the resource definition to fully comply with the actual deployment. One thing I can't get exactly right is the metadata, namely the container spec (gce-container-declaration).

I have followed the example in this repo and created a module, where I defined everything to my best knowledge. However, when I run terraform plan, I get a tiny difference in indentation:

```
  ~ metadata             = {
      ~ "gce-container-declaration" = <<~EOT
          + ---
            spec:
              containers:
          -     - name: service-memcached
          -       image: launcher.gcr.io/google/memcached1
          -       stdin: false
          -       tty: false
          +   - image: launcher.gcr.io/google/memcached1
          +     name: service-memcached
          +     stdin: false
          +     tty: false
              restartPolicy: Always
          - 
          - # This container declaration format is not public API and may change without notice. Please
          - # use gcloud command-line tool or Google Cloud Console to run Containers on Google Compute Engine.
          +   volumes: []
        EOT
        "google-logging-enabled"    = "true"
    }
```

Is the indentation difference negligible, or am I missing something in the definition?

**Module definition:**

```
module "gce-container" {
  source = "github.com/terraform-google-modules/terraform-google-container-vm"

  container = {
    name = "service-memcached"
    image = "launcher.gcr.io/google/memcached1"
    stdin = false
    tty = false
  }

  restart_policy = "Always"
}
```

Thanks a lot!

**Comment by aaron-lane** [comment]
Hi @svachmic!

YAML indentation is a bit flexible. The two parts of the diff should be functionally equivalent.

**Comment by svachmic** [comment]
Thank you! I was <hoping> that was the case, but wasn't 100% sure. I'll run it and report if anything broke 😅

**Comment by svachmic** [comment]
After a few days of testing, I'm confirming, that indeed, the YAML structure is really that flexible and nothing has changed after hitting `apply`. Thanks a lot for the help!
