### ISSUE TITLE
Output source image project and family

### ISSUE THREAD

**Issue by AdamMAtWork** [terraform-google-modules/terraform-google-container-vm#61]
In order to use this module with `terraform-google-vm/modules/instance_template` (v.2.1.0), one must hack up input values for the variables `source_image_project` and `source_image_family`.

I did this to get the image name, project and family:

```hcl
module "container" {
  source  = "terraform-google-container-vm"
  ...
}

data "google_compute_image" "cos" {
  name    = element(reverse(split("/", module.container.source_image)), 0)
  project = element(reverse(split("/", module.container.source_image)), 3)
}

module "instance_template" {
  source = "../terraform-google-vm/modules/instance_template"

  source_image         = data.google_compute_image.cos.name
  source_image_project = data.google_compute_image.cos.project
  source_image_family  = data.google_compute_image.cos.family
  ...
}
```

Since this module does the selection of the image project and family, it ought to add them to the output.

To make the output more generally useful, the entire data object could be output, instead of individual fields:
```hcl
output "source_image_object" {
  value       = data.google_compute_image.coreos
}
```
Then I can pick the details I need.

**Comment by morgante** [comment]
This seems like a reasonable addition, happy to accept a pull request.

**Comment by AdamMAtWork** [comment]
Thanks @morgante I have supplied a PR
