### ISSUE TITLE
Cannot apply a version constraint to module "gce-container" because it has a non Registry URL.

### ISSUE THREAD

**Issue by kevinsimper** [terraform-google-modules/terraform-google-container-vm#64]
When I try to run the example in the readme I get meet with

```
$ terraform init
Initializing modules...
Downloading github.com/terraform-google-modules/terraform-google-container-vm for gce-container...

Error: Invalid version constraint

Cannot apply a version constraint to module "gce-container" (at
container.tf:1) because it has a non Registry URL.
```

Easy solution is just to remove it, but it is just confusing that it doesn't work :)

$ terraform version
Terraform v0.12.25
+ provider.google v3.21.0

**Comment by morgante** [comment]
Turns out we had the wrong link listed in the README.

The right reference is `terraform-google-modules/container-vm/google`.

https://registry.terraform.io/modules/terraform-google-modules/container-vm/google/2.0.0

**Comment by kevinsimper** [comment]
@morgante There are two examples in the readme :)
