### ISSUE TITLE
Host mode in COS is unable to map firewall network access

### ISSUE THREAD

**Issue by jjperezaguinaga** [terraform-google-modules/terraform-google-container-vm#65]
I'm running the following [container](gcr.io/hoprassociation/hopr-core@sha256:a6ee48f53acaccf9ff57189464a43079705d07aae2e5c757c760182cce670afe) via Terraform using the following [scripts](https://github.com/hoprnet/hopr-devops/blob/ch-develop/ch/develop/services/hopr-bootstrap/main.tf) to deploy it to the default COS (right now that's [84](https://cloud.google.com/container-optimized-os/docs/release-notes#cos-dev-84-13078-0-0)). Ideally, the COS would be able to map the ports required (e.g. `9091`) as the [documentation describes about firewall rules](https://cloud.google.com/compute/docs/containers/deploying-containers#configuring_firewall_rules), due to Docker's [Host mode](https://docs.docker.com/engine/reference/run/#network-settings).

However, when I run the container (a [libp2p](https://github.com/libp2p/js-libp2p) chat app), the network access seems to be insufficient for other nodes to reach it. For instance, on my machine at `34.65.119.138` the app is listening to port 9091 at the following interfaces:

![image](https://user-images.githubusercontent.com/1128312/83427774-8e8a4300-a431-11ea-9b66-f34b8119ec4e.png)

However, other nodes running the same app are unable to reach it. Here's my `docker ps` output:

```
daneel@hopr-ch-develop-bootstrap-001-35cc374a ~ $ docker ps --no-trunc
CONTAINER ID                                                       IMAGE                                                                  COMMAND                                                 CREATED             STATUS              PORTS               NAMES
f47835941cf6e9cbc2b219e4679f1b3660ee036d0699ff22c9858813a2306397   gcr.io/stackdriver-agents/stackdriver-monitoring-agent:0.2-5.5.2-379   "/bin/sh -c /run.sh"                                    26 minutes ago      Up 26 minutes                           stackdriver-monitoring-agent
6edbc96895edb3f7d8581e6c62d170f104ff7e2fed23c539a3547b44bf3def7c   gcr.io/hoprassociation/hopr-core:nat-traversal-rc                      "node ./lib/index.js -b -p 111111"                      33 minutes ago      Up 26 minutes                           klt--pkkh
8c9fce9dcf2c7e8c104b99f4634039d8a3ba024cfe03a06b02d388bb93c51496   gcr.io/stackdriver-agents/stackdriver-logging-agent:0.2-1.5.33-1-1     "/entrypoint.sh /usr/sbin/google-fluentd"               34 minutes ago      Up 34 minutes                           stackdriver-logging-agent
474339a103b068bbb7d5267cd29340363132804eaa46020fee8ca80c198dd6d2   gcr.io/stackdriver-agents/stackdriver-metadata-agent:0.2-0.0.17-2      "/bin/sh -c /opt/stackdriver/metadata/sbin/metadatad"   34 minutes ago      Up 34 minutes       8000/tcp            stackdriver-metadata-agent
```
As we can see, the port is not exposed to port 9091. Now, if I stop the container and restart it with the `-p` settings manually (i.e. `docker run -v /var/hopr/db:/app/db -e HOST_IPV4=$HOST_IPV4 -e BOOTSTRAP_SERVERS=$BOOTSTRAP_SERVERS -e ETHEREUM_PROVIDER=$ETHEREUM_PROVIDER -p $PORTS --name bootstrap-node -itd $DOCKER_IMAGE -b -p 111111` where `$PORTS=9091:9091`), I get the following output on `docker ps`:

```
daneel@hopr-ch-develop-bootstrap-001-35cc374a ~ $ docker ps --no-trunc
CONTAINER ID                                                       IMAGE                                                                  COMMAND                                                 CREATED             STATUS              PORTS                                   NAMES
7cfac2bb5f2a59470bb285242b6aebf7c425db1260d61536bcaa9aad15c0fca0   gcr.io/hoprassociation/hopr-core:latest                                "node ./lib/index.js -b -p 111111"                      19 seconds ago      Up 18 seconds       0.0.0.0:9091->9091/tcp, 9092-9095/tcp   bootstrap-node
f47835941cf6e9cbc2b219e4679f1b3660ee036d0699ff22c9858813a2306397   gcr.io/stackdriver-agents/stackdriver-monitoring-agent:0.2-5.5.2-379   "/bin/sh -c /run.sh"                                    29 minutes ago      Up 29 minutes                                               stackdriver-monitoring-agent
8c9fce9dcf2c7e8c104b99f4634039d8a3ba024cfe03a06b02d388bb93c51496   gcr.io/stackdriver-agents/stackdriver-logging-agent:0.2-1.5.33-1-1     "/entrypoint.sh /usr/sbin/google-fluentd"               36 minutes ago      Up 36 minutes                                               stackdriver-logging-agent
474339a103b068bbb7d5267cd29340363132804eaa46020fee8ca80c198dd6d2   gcr.io/stackdriver-agents/stackdriver-metadata-agent:0.2-0.0.17-2      "/bin/sh -c /opt/stackdriver/metadata/sbin/metadatad"   36 minutes ago      Up 36 minutes       8000/tcp                                stackdriver-metadata-agent
```

In this, I get the following interfaces exposed:
![image](https://user-images.githubusercontent.com/1128312/83428051-0193b980-a432-11ea-9939-7e00dedd9b31.png)

When doing the latter (i.e. starting the container manually outside the COS wrapper (I believe Klotet?), my application can connect successfully.

The practical question is the following:
- Are there any settings we could tweak in the Terraform module to allow this manual configuration of the port while still retaining the container management workflow?
- Is there any documentation on setting a custom COS to allow these requirements (alongside logging, for instance, already mentioned in #60).

**Comment by morgante** [comment]
The standard configuration *should* support 1-to-1 ports (ie. port 9091 on the container will be exposed as port 9091 on the host) but no mapping is supported.

This is the underlying agent being used: https://github.com/GoogleCloudPlatform/konlet

You can also try with gcloud commands to see if it works and then check the generated metadata: https://cloud.google.com/compute/docs/containers/configuring-options-to-run-containers

**Comment by jjperezaguinaga** [comment]
@morgante Thanks for the pointers! I've actually ran the following `gcloud` command to have a better idea on the issue in question.

```
gcloud compute instances create-with-container hopr-demo \
   --container-image gcr.io/hoprassociation/hopr-core:latest \
   --container-arg="-b" \
   --container-arg="-p 123456" \
   --container-mount-host-path mount-path=/app/db,host-path=/var/hopr/db,mode=rw \
   --container-stdin \
   --container-env HOST_IPV4=0.0.0.0:9091,ETHEREUM_PROVIDER=wss://kovan.infura.io/ws/v3/$INFURA_ID \
   --tags hopr-node
```
followed by the port firewall command
```
gcloud compute firewall-rules create allow-hopr \
   --allow tcp:9091 --target-tags hopr-node
```

I can confirm that my container is up and running when I SSH into the instance:
```
jjperezaguinaga@hopr-demo ~ $ docker ps --no-trunc
CONTAINER ID                                                       IMAGE                                                                COMMAND                                     CREATED             STATUS              PORTS               NAMES
ba16134c57110ee1d770dfcf8e02846ea0e9d4bb149133c59d602c26971ff37f   gcr.io/hoprassociation/hopr-core:latest                              "node ./lib/index.js -b '-p 123456'"        6 minutes ago       Up 3 minutes                            klt-hopr-demo-jgbc
388adefc9fa40405cc39ef6b9f3fb6ffb0025ca126a52435a8b1bc3acad31ad0   gcr.io/stackdriver-agents/stackdriver-logging-agent:0.2-1.5.33-1-1   "/entrypoint.sh /usr/sbin/google-fluentd"   6 minutes ago       Up 6 minutes                            stackdriver-logging-agent
```
I can also confirm the host understands the docker container port and mounts it properly using `netstat`
```
jjperezaguinaga@hopr-demo ~ $ netstat -tlnp
(No info could be read for "-p": geteuid()=20141 but you should be root.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:32859         0.0.0.0:*               LISTEN      -
tcp        1      0 0.0.0.0:9091            0.0.0.0:*               LISTEN      -
```
I can also connect to the container port, and even from my workstation using `nc`, even testing other ports to ensure its not just a false positive:
```
jjperezaguinaga@hopr-demo ~ $ nc 127.0.0.1 -zv 9091
localhost [127.0.0.1] 9091 (?) open
jjperezaguinaga@hopr-demo ~ $ nc 127.0.0.1 -zv 9092
localhost [127.0.0.1] 9092 (?) : Connection refused
jjperezaguinaga@hopr-demo ~ $ exit
logout
Connection to 34.65.139.63 closed.
➜  hopr-devops git:(ch-develop) ✗ nc 34.65.139.63 -zv 9091
Connection to 34.65.139.63 port 9091 [tcp/xmltec-xmlmail] succeeded!
➜  hopr-devops git:(ch-develop) ✗ nc 34.65.139.63 -zv 9092
^C 
```
Yet, my process is unable to connect to it... now I kill the [Konlet](https://github.com/GoogleCloudPlatform/konlet) container (unsure if that's the right expression tho), and I can confirm that my previous tests don't work.
```
jjperezaguinaga@hopr-demo ~ $ docker stop klt-hopr-demo-jgbc
klt-hopr-demo-jgbc
jjperezaguinaga@hopr-demo ~ $ nc 127.0.0.1 -zv 9091
localhost [127.0.0.1] 9091 (?) : Connection refused
jjperezaguinaga@hopr-demo ~ $ exit
logout
Connection to 34.65.139.63 closed.
➜  hopr-devops git:(ch-develop) ✗ nc 34.65.139.63 -zv 9091                                              nc: connectx to 34.65.139.63 port 9091 (tcp) failed: Connection refused
```
However, if I restart the container manually with the `-p` flag attached to it, I can actually connect via my process from my workstation:

```
docker run -v /var/hopr/db:/app/db -e HOST_IPV4=$HOST_IPV4 -e BOOTSTRAP_SERVERS=$BOOTSTRAP_SERVERS -e ETHEREUM_PROVIDER=$ETHEREUM_PROVIDER -p $PORTS --name bootstrap-node -itd $DOCKER_IMAGE -b -p 123456
```

This will return the following message from my container, showcasing the successful connection from my process:

```
Available under the following addresses:
 /ip4/34.65.139.63/tcp/9091/p2p/16Uiu2HAmSmcSiAfnhpBSYdRzpiW1eesx3UiD73eC7sJLStrKaQHm
 /ip4/127.0.0.1/tcp/9091/p2p/16Uiu2HAmSmcSiAfnhpBSYdRzpiW1eesx3UiD73eC7sJLStrKaQHm
 /ip4/172.17.0.3/tcp/9091/p2p/16Uiu2HAmSmcSiAfnhpBSYdRzpiW1eesx3UiD73eC7sJLStrKaQHm

... running as bootstrap node!.
Incoming connection from 16Uiu2HAkv9wwnziYoV6pc3MVqM13TSqLFTTKMefdR2EyeUMDPZES.
```

So it seems that the best place to point this issue is in the Konlet repository, as it seems there's something in the way it “wraps” the container metadata that isn't a 1 to 1 representation of the actual container connection, and not really this module implementation which I used to create these machines.

Closing this. If there are any pointers or ideas on work around or diagnostic approaches on how to tackle this, those would be highly appreciated.

**Comment by morgante** [comment]
@jjperezaguinaga Thanks for following up. My only tip would be to continue working with the `gcloud` commands until you have a working config you're satisfied with, then attempt to backport the metadata on the VM into the Terraform module.

**Comment by jjperezaguinaga** [comment]
@morgante No worries, au contraire, thanks for the quick responses in the thread. I've managed to get it working, so going to share some thoughts in case someone stumbles upon the same issue. I'm taking some bits from here and the [Konlet](https://github.com/GoogleCloudPlatform/konlet) repository, which I recommend anyone using the `create-with-container` or using this module to check out.

In short, I had to run the following `iptables` run as `root` to allow the traffic from the machine to be reachable on the given port.

```
iptables -D INPUT -p tcp --dport 9091 -j ACCEPT
```

I believe that even though that the default configuration might work for most containers on the `host` mode, for some odd reason mine (and perhaps others) needed explicitly to be opened via `iptables`. This is extremely weird as my `nc` tests showed that w/o the extra rule I was able to reach the port, but still my process was unable to talk to it.

Now, part of the issue I believe comes from the way Konlet starts up the container. I was unable to find the Ignition Config it uses to start everything up, but reading the [modules](https://github.com/terraform-google-modules/terraform-google-container-vm/tree/master/modules) in this repository, my guess is that its configuration is similar to the [generic](https://github.com/terraform-google-modules/terraform-google-container-vm/blob/master/modules/cos-generic/assets/cloud-config.yaml) one with some sprinkled magic similar as the [coredns](https://github.com/terraform-google-modules/terraform-google-container-vm/blob/master/modules/cos-coredns/assets/cloud-config.yaml) one parses some variables from the Terraform module. It seems that given their [startup script network configuration](https://github.com/GoogleCloudPlatform/konlet/blob/master/gce-containers-startup/runtime/runtime.go#L308) no `iptables` rules are added, unlike the `cloud-config.yaml` files I just linked. I'll follow on the Konlet repository to see if there's a way to configure this option on demand and/or given a specific metadata key.

As a final note, I tried using `user-data` directly instead of the `terraform-google-modules/container-vm/google` module that replaces the `gce-container-declaration`, i.e. producing my own Ignition Config file and try to then add the required `iptables` rules alongside the `gcplogs` flags (mentioned in #60). However, this (of course) replaced Konlet entirely and left me with handling everything with `systemd` which well, is a bit annoying and defeats the purpose of using the COS images. Anyway, for anyone trying to go down that road, I wouldn't recommend it unless you have a very specific use case such as the ones described in the images.

Now I can get the node working, and I'll move to see if there's a way to get the `gcplogs` log driver working next. That's, though, a conversation for https://github.com/GoogleCloudPlatform/konlet/issues/56. Thanks for all the help, perhaps after I wrap everything I'll send a post in the [community](https://github.com/GoogleCloudPlatform/community) repository.
