### ISSUE TITLE
Host directory mount example is missing

### ISSUE THREAD

**Issue by jufi** [terraform-google-modules/terraform-google-container-vm#66]
Thank you for providing this module. I still try to figure out, how to provide host directory mounts e.g. to mount a config file into the docker container like that:

![Screenshot 2020-07-17 at 15 54 39](https://user-images.githubusercontent.com/2759114/87793673-da5c4480-c845-11ea-9400-fb2203751f2d.png)

Unfortunately the documentation does not cover that use case.

Thanks in advance!

**Comment by bharathkkb** [comment]
Hi @jufi 
Does this example https://github.com/terraform-google-modules/terraform-google-container-vm/blob/bff2870792a2b048b531a273cc2a2ce6b6ae3043/examples/instance_with_attached_disk/main.tf#L39 cover this usecase?

**Comment by jufi** [comment]
Thanks for answering. The example you referenced is mounting an empty tmpfs file system into the container and a persistent disk as a data volume, but not mounting a host directory as a data volume (this is a possible meta data configuration for container deployment  (see https://cloud.google.com/compute/docs/containers/configuring-options-to-run-containers#gcloud_8))

<img width="408" alt="Screenshot 2020-07-20 at 08 52 31" src="https://user-images.githubusercontent.com/2759114/87913053-bd568a00-ca6e-11ea-9b13-9e2ba8d5deb1.png">

**Comment by jufi** [comment]
I figured it out. In my particular example from above, the configuration would look like that:

```
container = {
    image = "nginx:1.17"
    volumeMounts = [
      {
        mountPath = "/etc/nginx/"
        name      = "host-path"
        readOnly  = true
      }
    ]
  }

  volumes = [
    {
      name = "host-path"
      hostPath = {
        path = "/home/conf/nginx"
      }
    }
  ]
```

**Comment by morgante** [comment]
It would be great to add this to one of the examples actually.

**Comment by endurance** [comment]
How did you find that hostPath is an available option?

I am having some difficulty identifying the available options for these keys

**Comment by endurance** [comment]
https://github.com/GoogleCloudPlatform/konlet/blob/master/gce-containers-startup/gce-containers-startup_test.go

gce-container-declartion is parsed by konlet - the container orchestration tool within GCE VMs.

This might help others, so posting it up.
