### ISSUE TITLE
ERROR: Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.

### ISSUE THREAD

**Issue by tejasved-q** [terraform-google-modules/terraform-google-container-vm#71]
![image](https://user-images.githubusercontent.com/61696164/116124040-6490dd80-a6e1-11eb-8c4e-85d7cdf03268.png)

Getting the following error.

**Comment by tejasved-q** [comment]
Temporary solution: typecasted/converted the reference in module to nonsensitive.

ref: [https://www.terraform.io/docs/language/functions/nonsensitive.html](https://www.terraform.io/docs/language/functions/nonsensitive.html)

**Comment by bharathkkb** [comment]
@tejasved-q happy to review a PR to fix this.
Example PR: https://github.com/terraform-google-modules/terraform-google-vm/pull/164
