### ISSUE TITLE
Using local SSD volumes with containers

### ISSUE THREAD

**Issue by dvasdekis** [terraform-google-modules/terraform-google-container-vm#74]
Hi folks,

Not a bug, but I am looking for ideas on this.

So we run a few stateless containers that do some intense local I/O, and I was wondering if there's some way to use 'local SSD' storage as the volume where COS runs the container from. For my use case, I don't give the slightest toot if the SSD gets blown away, and I'd even prefer it to happen once a week rather than clearing out my temp folder via a script.

I couldn't figure out how to define a local SSD in your terraform template - is there an example somewhere?

Thanks!

**Comment by morgante** [comment]
I don't think the container config cares if the disk happens to be a local SSD, so you can likely adapt [this example](https://github.com/terraform-google-modules/terraform-google-container-vm/blob/master/examples/instance_with_attached_disk/main.tf) to work for you.
